# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_auto_20160603_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userdefined_display_name',
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='default', max_length=150),
            preserve_default=False,
        ),
    ]
