# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20160531_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='display_name',
            new_name='userdefined_display_name',
        ),
    ]
